import gleam/erlang/os
import gleam/erlang/process
import gleam/http.{Post}
import gleam/json
import gleam/list
import gleam/string
import mist
import simplifile
import wisp
import wisp/wisp_mist

pub fn main() {
  wisp.configure_logger()

  let secret = wisp.random_string(64)
  let handler = wisp_mist.handler(handle_request, secret)

  let assert Ok(_) =
    mist.new(handler)
    |> mist.bind("0.0.0.0")
    |> mist.port(8000)
    |> mist.start

  process.sleep_forever()
}

pub fn handle_request(req: wisp.Request) -> wisp.Response {
  use <- wisp.log_request(req)
  use <- wisp.rescue_crashes
  use req <- wisp.handle_head(req)

  case wisp.path_segments(req) {
    [] -> serve_index()
    ["static", ..rest] -> serve_static(rest)
    ["api", "install"] -> handle_install(req)
    _ -> wisp.not_found()
  }
}

fn serve_index() -> wisp.Response {
  // Serve the React build index.html
  case simplifile.read("frontend/build/index.html") {
    Ok(html) -> wisp.html_response(html, 200)
    Error(_) -> {
      // Fallback to old templates location for development
      case simplifile.read("templates/index.html") {
        Ok(html) -> wisp.html_response(html, 200)
        Error(_) -> wisp.not_found()
      }
    }
  }
}

fn serve_static(path: List(String)) -> wisp.Response {
  // Validate path segments to prevent directory traversal
  case validate_path_segments(path) {
    False -> wisp.bad_request()
    True -> {
      // Try React build directory first, then fall back to old static directory
      let react_path = "frontend/build/static/" <> string.join(path, "/")
      let legacy_path = "static/" <> string.join(path, "/")

      case simplifile.read(react_path) {
        Ok(content) -> serve_static_content(react_path, content)
        Error(_) -> {
          case simplifile.read(legacy_path) {
            Ok(content) -> serve_static_content(legacy_path, content)
            Error(_) -> wisp.not_found()
          }
        }
      }
    }
  }
}

fn serve_static_content(file_path: String, content: String) -> wisp.Response {
  let content_type = get_content_type(file_path)

  wisp.response(200)
  |> wisp.set_header("content-type", content_type)
  |> wisp.string_body(content)
}

fn get_content_type(file_path: String) -> String {
  case True {
    _ if string.ends_with(file_path, ".css") -> "text/css"
    _ if string.ends_with(file_path, ".js") -> "application/javascript"
    _ if string.ends_with(file_path, ".json") -> "application/json"
    _ if string.ends_with(file_path, ".svg") -> "image/svg+xml"
    _ if string.ends_with(file_path, ".png") -> "image/png"
    _ if string.ends_with(file_path, ".ico") -> "image/x-icon"
    _ if string.ends_with(file_path, ".woff") -> "font/woff"
    _ if string.ends_with(file_path, ".woff2") -> "font/woff2"
    _ if string.ends_with(file_path, ".ttf") -> "font/ttf"
    _ -> "text/plain"
  }
}

fn validate_path_segments(segments: List(String)) -> Bool {
  // Reject any segment containing "..", ".", or starting with "/"
  // This prevents path traversal attacks like ../../../etc/passwd
  list.all(segments, fn(segment) {
    !string.contains(segment, "..") &&
    segment != "." &&
    segment != "" &&
    !string.starts_with(segment, "/")
  })
}

fn handle_install(req: wisp.Request) -> wisp.Response {
  case req.method {
    Post -> {
      use _body <- wisp.require_string_body(req)

      let _ = create_default_env()
      let _ = simplifile.create_directory_all("./auth")
      let _ = create_auth_file()

      install_response()
    }
    _ -> wisp.method_not_allowed([Post])
  }
}

fn install_response() -> wisp.Response {
  let updates = [
    json.object([#("progress", json.int(10)), #("status", json.string("✓ Configuration received"))]),
    json.object([#("progress", json.int(40)), #("status", json.string("✓ .env file created"))]),
    json.object([#("progress", json.int(60)), #("status", json.string("✓ Auth directory created"))]),
    json.object([#("progress", json.int(100)), #("status", json.string("✓ Installation complete!")), #("complete", json.bool(True))]),
  ]

  let body =
    list.map(updates, fn(obj) { json.to_string(obj) <> "\n" })
    |> string.join("")

  wisp.response(200)
  |> wisp.set_header("content-type", "application/json")
  |> wisp.string_body(body)
}

fn create_default_env() -> Result(Nil, simplifile.FileError) {
  // Copy .env.example to .env
  case simplifile.read(".env.example") {
    Ok(content) -> simplifile.write(to: ".env", contents: content)
    Error(_) -> {
      // Fallback if .env.example doesn't exist
      let content = "# Generated by Zone Web Installer\n"
      simplifile.write(to: ".env", contents: content)
    }
  }
}

fn create_auth_file() -> Result(Nil, simplifile.FileError) {
  // Generate a secure random password
  let password = generate_secure_password()

  // Create htpasswd entry using bcrypt
  case create_htpasswd_entry("admin", password) {
    Ok(htpasswd_content) -> {
      // Write the htpasswd file
      case simplifile.write(to: "./auth/users.htpasswd", contents: htpasswd_content) {
        Ok(_) -> {
          // Write password to a separate file for user reference
          let password_info = "# GENERATED ADMIN CREDENTIALS\n# Username: admin\n# Password: " <> password <> "\n\n# IMPORTANT: Save this password securely and delete this file!\n# You can change the password later with: htpasswd -B auth/users.htpasswd admin\n"
          let _ = simplifile.write(to: "./auth/ADMIN_PASSWORD.txt", contents: password_info)
          Ok(Nil)
        }
        Error(e) -> Error(e)
      }
    }
    Error(e) -> Error(e)
  }
}

fn generate_secure_password() -> String {
  // Generate a cryptographically secure random password
  // Using base64-like encoding of random bytes for readability
  let chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
  let length = 24

  // Use wisp's random_string which uses crypto-secure RNG
  wisp.random_string(length)
}

fn create_htpasswd_entry(username: String, password: String) -> Result(String, simplifile.FileError) {
  // Use htpasswd command to generate bcrypt hash
  // This requires apache2-utils to be installed in the Docker container (already is)
  let command = "htpasswd -nbB '" <> username <> "' '" <> password <> "'"

  // Use Erlang's os:cmd to execute the command
  let output = os.system(command)

  // Check if command succeeded (htpasswd returns username:hash format)
  case string.contains(output, ":") {
    True -> Ok(output)
    False -> {
      // Fallback: if htpasswd fails, create a plain entry (not ideal but documented)
      Ok(username <> ":" <> password <> "\n# WARNING: Password stored in plaintext - htpasswd not available\n")
    }
  }
}
