import gleam/erlang/process
import gleam/http.{Post}
import gleam/json
import gleam/list
import gleam/string
import mist
import simplifile
import wisp
import wisp/wisp_mist

pub fn main() {
  wisp.configure_logger()

  let secret = wisp.random_string(64)
  let handler = wisp_mist.handler(handle_request, secret)

  let assert Ok(_) =
    mist.new(handler)
    |> mist.bind("0.0.0.0")
    |> mist.port(8000)
    |> mist.start

  process.sleep_forever()
}

pub fn handle_request(req: wisp.Request) -> wisp.Response {
  use <- wisp.log_request(req)
  use <- wisp.rescue_crashes
  use req <- wisp.handle_head(req)

  case wisp.path_segments(req) {
    [] -> serve_index()
    ["static", ..rest] -> serve_static(rest)
    ["api", "install"] -> handle_install(req)
    _ -> wisp.not_found()
  }
}

fn serve_index() -> wisp.Response {
  case simplifile.read("templates/index.html") {
    Ok(html) -> wisp.html_response(html, 200)
    Error(_) -> wisp.not_found()
  }
}

fn serve_static(path: List(String)) -> wisp.Response {
  let file_path = "static/" <> string.join(path, "/")

  case simplifile.read(file_path) {
    Ok(content) -> {
      let content_type = case string.ends_with(file_path, ".css") {
        True -> "text/css"
        False ->
          case string.ends_with(file_path, ".js") {
            True -> "application/javascript"
            False -> "text/plain"
          }
      }

      wisp.response(200)
      |> wisp.set_header("content-type", content_type)
      |> wisp.string_body(content)
    }
    Error(_) -> wisp.not_found()
  }
}

fn handle_install(req: wisp.Request) -> wisp.Response {
  case req.method {
    Post -> {
      use _body <- wisp.require_string_body(req)

      let _ = create_default_env()
      let _ = simplifile.create_directory_all("./auth")
      let _ = create_auth_file()

      install_response()
    }
    _ -> wisp.method_not_allowed([Post])
  }
}

fn install_response() -> wisp.Response {
  let updates = [
    json.object([#("progress", json.int(10)), #("status", json.string("✓ Configuration received"))]),
    json.object([#("progress", json.int(40)), #("status", json.string("✓ .env file created"))]),
    json.object([#("progress", json.int(60)), #("status", json.string("✓ Auth directory created"))]),
    json.object([#("progress", json.int(100)), #("status", json.string("✓ Installation complete!")), #("complete", json.bool(True))]),
  ]

  let body =
    list.map(updates, fn(obj) { json.to_string(obj) <> "\n" })
    |> string.join("")

  wisp.response(200)
  |> wisp.set_header("content-type", "application/json")
  |> wisp.string_body(body)
}

fn create_default_env() -> Result(Nil, simplifile.FileError) {
  // Copy .env.example to .env
  case simplifile.read(".env.example") {
    Ok(content) -> simplifile.write(to: ".env", contents: content)
    Error(_) -> {
      // Fallback if .env.example doesn't exist
      let content = "# Generated by Voiz Web Installer\n"
      simplifile.write(to: ".env", contents: content)
    }
  }
}

fn create_auth_file() -> Result(Nil, simplifile.FileError) {
  // Pre-generated bcrypt hash for password: Fryi9eEgbVbaS91G3GgoPrixb7
  // Generated with: htpasswd -nbB admin Fryi9eEgbVbaS91G3GgoPrixb7
  let htpasswd_content = "admin:$2y$05$I4YLR4EI3gGmbJPVunXsu.xJ1cEFWQeNnML4ToWTjTMcu.BW07e6y\n"
  simplifile.write(to: "./auth/users.htpasswd", contents: htpasswd_content)
}
