//! Zone Installer - Web-based configuration wizard backend
//!
//! Serves the React frontend and handles installation requests.

use axum::{
    Router,
    body::Body,
    http::{StatusCode, header},
    response::{Html, IntoResponse, Response},
    routing::{get, post},
};
use rand::Rng;
use std::path::Path;
use tokio::{fs, process::Command};
use tower_http::services::ServeDir;
use tracing_subscriber::{layer::SubscriberExt, util::SubscriberInitExt};

const FRONTEND_DIR: &str = "frontend/build";

#[tokio::main]
async fn main() {
    // Initialize tracing
    tracing_subscriber::registry()
        .with(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| "zone_installer=info".into()),
        )
        .with(tracing_subscriber::fmt::layer())
        .init();

    tracing::info!("Starting Zone installer...");

    let app = Router::new()
        .route("/", get(serve_index))
        .route("/api/install", post(handle_install))
        .nest_service("/static", ServeDir::new(format!("{}/static", FRONTEND_DIR)));

    let listener = tokio::net::TcpListener::bind("0.0.0.0:8000")
        .await
        .expect("Failed to bind to port 8000");

    tracing::info!("Listening on http://0.0.0.0:8000");

    axum::serve(listener, app).await.expect("Server error");
}

/// Serve the index.html file
async fn serve_index() -> impl IntoResponse {
    let index_path = format!("{}/index.html", FRONTEND_DIR);

    match fs::read_to_string(&index_path).await {
        Ok(html) => Html(html).into_response(),
        Err(_) => {
            tracing::error!("Failed to read index.html from {}", index_path);
            (StatusCode::NOT_FOUND, "Frontend not found").into_response()
        }
    }
}

/// Handle the installation request
async fn handle_install() -> impl IntoResponse {
    let updates = vec![
        InstallUpdate::progress(10, "Configuration received"),
        InstallUpdate::progress(30, "Creating .env file..."),
    ];

    // Create .env file
    let env_result = create_default_env().await;
    let mut all_updates = updates;

    match env_result {
        Ok(_) => {
            all_updates.push(InstallUpdate::progress(40, ".env file created"));
        }
        Err(e) => {
            all_updates.push(InstallUpdate::error(&format!(
                "Failed to create .env: {}",
                e
            )));
            return streaming_response(all_updates);
        }
    }

    // Create auth directory
    all_updates.push(InstallUpdate::progress(50, "Creating auth directory..."));

    if let Err(e) = fs::create_dir_all("./auth").await {
        all_updates.push(InstallUpdate::error(&format!(
            "Failed to create auth directory: {}",
            e
        )));
        return streaming_response(all_updates);
    }

    all_updates.push(InstallUpdate::progress(60, "Auth directory created"));

    // Create htpasswd file
    all_updates.push(InstallUpdate::progress(
        70,
        "Generating admin credentials...",
    ));

    match create_auth_file().await {
        Ok(_) => {
            all_updates.push(InstallUpdate::progress(90, "Admin credentials created"));
        }
        Err(e) => {
            all_updates.push(InstallUpdate::error(&format!(
                "Failed to create auth file: {}",
                e
            )));
            return streaming_response(all_updates);
        }
    }

    // Complete
    all_updates.push(InstallUpdate::complete(100, "Installation complete!"));

    streaming_response(all_updates)
}

/// Create the .env file from .env.example or generate a default one
async fn create_default_env() -> Result<(), std::io::Error> {
    let env_example = Path::new(".env.example");

    let content = if env_example.exists() {
        fs::read_to_string(env_example).await?
    } else {
        "# Generated by Zone Web Installer\n".to_string()
    };

    fs::write(".env", content).await
}

/// Create the htpasswd file with a generated admin password
async fn create_auth_file() -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    let password = generate_secure_password();

    // Try to use htpasswd command for bcrypt hash
    let htpasswd_content = create_htpasswd_entry("admin", &password).await?;

    // Write htpasswd file
    fs::write("./auth/users.htpasswd", &htpasswd_content).await?;

    // Write password reference file
    let password_info = format!(
        "# GENERATED ADMIN CREDENTIALS\n\
         # Username: admin\n\
         # Password: {}\n\n\
         # IMPORTANT: Save this password securely and delete this file!\n\
         # You can change the password later with: htpasswd -B auth/users.htpasswd admin\n",
        password
    );
    fs::write("./auth/ADMIN_PASSWORD.txt", password_info).await?;

    Ok(())
}

/// Generate a cryptographically secure random password
fn generate_secure_password() -> String {
    const CHARSET: &[u8] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
    let mut rng = rand::thread_rng();

    (0..24)
        .map(|_| {
            let idx = rng.gen_range(0..CHARSET.len());
            CHARSET[idx] as char
        })
        .collect()
}

/// Create an htpasswd entry using the htpasswd command (bcrypt)
async fn create_htpasswd_entry(
    username: &str,
    password: &str,
) -> Result<String, Box<dyn std::error::Error + Send + Sync>> {
    let output = Command::new("htpasswd")
        .args(["-nbB", username, password])
        .output()
        .await;

    match output {
        Ok(output) if output.status.success() => {
            let result = String::from_utf8_lossy(&output.stdout).to_string();
            Ok(result)
        }
        Ok(output) => {
            let stderr = String::from_utf8_lossy(&output.stderr);
            tracing::warn!("htpasswd failed: {}, using fallback", stderr);
            // Fallback if htpasswd fails
            Ok(format!(
                "{}:{}\n# WARNING: Password stored in plaintext - htpasswd not available\n",
                username, password
            ))
        }
        Err(e) => {
            tracing::warn!("htpasswd command not found: {}, using fallback", e);
            // Fallback if htpasswd is not installed
            Ok(format!(
                "{}:{}\n# WARNING: Password stored in plaintext - htpasswd not available\n",
                username, password
            ))
        }
    }
}

/// Installation update message
#[derive(serde::Serialize)]
struct InstallUpdate {
    progress: u8,
    status: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    complete: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    error: Option<bool>,
}

impl InstallUpdate {
    fn progress(progress: u8, status: &str) -> Self {
        Self {
            progress,
            status: format!("✓ {}", status),
            complete: None,
            error: None,
        }
    }

    fn complete(progress: u8, status: &str) -> Self {
        Self {
            progress,
            status: format!("✓ {}", status),
            complete: Some(true),
            error: None,
        }
    }

    fn error(status: &str) -> Self {
        Self {
            progress: 0,
            status: format!("✗ {}", status),
            complete: None,
            error: Some(true),
        }
    }
}

/// Create a streaming JSON response from update messages
fn streaming_response(updates: Vec<InstallUpdate>) -> Response {
    let body: String = updates
        .into_iter()
        .filter_map(|u| serde_json::to_string(&u).ok())
        .map(|s| s + "\n")
        .collect();

    Response::builder()
        .status(StatusCode::OK)
        .header(header::CONTENT_TYPE, "application/json")
        .body(Body::from(body))
        .unwrap()
}
