# Minimal deployment example for Zone
environment: development

global:
  externalDatabase: true
  securityContexts: true

secrets:
  create: false
  existingSecret: "zone-minimal-secrets"

server:
  enabled: true
  replicaCount: 1
  autoscaling:
    enabled: false
  podDisruptionBudget:
    enabled: false

manager:
  enabled: true
  replicaCount: 1
  autoscaling:
    enabled: false
  podDisruptionBudget:
    enabled: false

ingress:
  enabled: false

migration:
  enabled: false
