{{- if and .Values.manager.enabled .Values.manager.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "zone-server.fullname" . }}-manager
  labels:
    {{- include "zone-server.manager.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.manager.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "zone-server.manager.selectorLabels" . | nindent 6 }}
{{- end }}
