{{- if .Values.manager.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "zone-server.fullname" . }}-manager
  labels:
    {{- include "zone-server.manager.labels" . | nindent 4 }}
spec:
  type: {{ .Values.manager.service.type }}
  ports:
    - port: {{ .Values.manager.service.port }}
      targetPort: {{ .Values.manager.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "zone-server.manager.selectorLabels" . | nindent 4 }}
{{- end }}
