#!/bin/bash
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

BLUE='\033[0;34m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

# Ensure Kind cluster exists
if ! kind get clusters 2>/dev/null | grep -q "zone-dev"; then
    echo -e "${RED}Kind cluster 'zone-dev' not found.${NC}"
    echo -e "${YELLOW}Run 'make kind-create' first.${NC}"
    exit 1
fi

# Switch context
kubectl config use-context kind-zone-dev

# Generate secrets if not exists
SECRETS_FILE="$PROJECT_ROOT/k8s/secrets.yaml"

if [ ! -f "$SECRETS_FILE" ]; then
    echo -e "${YELLOW}Generating development secrets...${NC}"

    # Generate random passwords
    POSTGRES_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)
    VALKEY_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)
    JWT_SECRET=$(openssl rand -base64 32 | tr -d '/+=' | head -c 48)
    ENCRYPTION_KEY=$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)
    LITELLM_MASTER_KEY=$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)
    LITELLM_SALT_KEY=$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)
    MANAGER_API_KEY=$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)

    cat > "$SECRETS_FILE" << EOF
# Generated by tilt-up.sh - DO NOT COMMIT
apiVersion: v1
kind: Secret
metadata:
  name: zone-secrets
  namespace: zone
type: Opaque
stringData:
  # PostgreSQL (used by CNPG bootstrap)
  postgres-password: "${POSTGRES_PASSWORD}"

  # Valkey
  valkey-password: "${VALKEY_PASSWORD}"

  # Application secrets
  jwt-secret: "${JWT_SECRET}"
  encryption-key: "${ENCRYPTION_KEY}"

  # LiteLLM
  litellm-master-key: "${LITELLM_MASTER_KEY}"
  litellm-salt-key: "${LITELLM_SALT_KEY}"

  # Manager API
  manager-api-key: "${MANAGER_API_KEY}"

  # Database connection string (for server)
  database-url: "postgresql://zone:${POSTGRES_PASSWORD}@zone-postgres-rw:5432/zone"

  # Valkey connection string (for server)
  valkey-url: "redis://default:${VALKEY_PASSWORD}@valkey:6379"
EOF

    echo -e "${GREEN}Secrets generated at $SECRETS_FILE${NC}"
    echo -e "${YELLOW}NOTE: This file contains sensitive data. Do not commit to git.${NC}"
fi

# Start Tilt
echo -e "${GREEN}Starting Tilt...${NC}"
cd "$PROJECT_ROOT/k8s"
tilt up "$@"
