#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

BLUE='\033[0;34m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

if ! kind get clusters 2>/dev/null | grep -q "^zone-dev$"; then
    echo -e "${RED}Kind cluster 'zone-dev' not found.${NC}"
    echo -e "${YELLOW}Run 'make kind-create' first.${NC}"
    exit 1
fi

kubectl config use-context kind-zone-dev

SECRETS_FILE="$PROJECT_ROOT/k8s/secrets.yaml"

if [ ! -f "$SECRETS_FILE" ]; then
    echo -e "${YELLOW}Generating development secrets...${NC}"

    POSTGRES_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)
    POSTGRES_SUPERUSER_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)
    VALKEY_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)
    JWT_SECRET=$(openssl rand -base64 32 | tr -d '/+=' | head -c 48)
    ENCRYPTION_KEY=$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)
    LITELLM_MASTER_KEY=$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)
    LITELLM_SALT_KEY=$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)
    MANAGER_API_KEY=$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)

    cat > "$SECRETS_FILE" << EOF
# Generated by tilt-up.sh - DO NOT COMMIT
---
apiVersion: v1
kind: Secret
metadata:
  name: zone-secrets
  namespace: zone
type: Opaque
stringData:
  # CNPG bootstrap.initdb.secret requires username + password
  username: zone
  password: "${POSTGRES_PASSWORD}"
  postgres-password: "${POSTGRES_PASSWORD}"

  # Valkey
  valkey-password: "${VALKEY_PASSWORD}"

  # Application secrets (JWT_SECRET and ENCRYPTION_KEY must be >= 32 chars)
  jwt-secret: "${JWT_SECRET}"
  encryption-key: "${ENCRYPTION_KEY}"

  # LiteLLM
  litellm-master-key: "${LITELLM_MASTER_KEY}"
  litellm-salt-key: "${LITELLM_SALT_KEY}"

  # Manager API
  manager-api-key: "${MANAGER_API_KEY}"

  # zone-server talks to the manager database
  database-url: "postgres://zone:${POSTGRES_PASSWORD}@zone-postgres-rw:5432/manager"

  # LiteLLM talks to its own database on the same cluster
  litellm-database-url: "postgres://zone:${POSTGRES_PASSWORD}@zone-postgres-rw:5432/litellm"

  valkey-url: "redis://:${VALKEY_PASSWORD}@valkey:6379"
---
apiVersion: v1
kind: Secret
metadata:
  name: zone-postgres-superuser
  namespace: zone
type: kubernetes.io/basic-auth
stringData:
  username: postgres
  password: "${POSTGRES_SUPERUSER_PASSWORD}"
EOF

    echo -e "${GREEN}Secrets generated at $SECRETS_FILE${NC}"
    echo -e "${YELLOW}NOTE: This file contains sensitive data. Do not commit to git.${NC}"
fi

echo -e "${GREEN}Starting Tilt...${NC}"
cd "$PROJECT_ROOT/k8s"
tilt up "$@"
