import { Window } from 'happy-dom';

const window = new Window({
  url: 'http://localhost:3000',
  width: 1024,
  height: 768,
});

// Register globals
Object.assign(globalThis, {
  window,
  document: window.document,
  navigator: window.navigator,
  location: window.location,
  history: window.history,
  HTMLElement: window.HTMLElement,
  HTMLInputElement: window.HTMLInputElement,
  HTMLSelectElement: window.HTMLSelectElement,
  HTMLTextAreaElement: window.HTMLTextAreaElement,
  HTMLButtonElement: window.HTMLButtonElement,
  Element: window.Element,
  Node: window.Node,
  Text: window.Text,
  DocumentFragment: window.DocumentFragment,
  Event: window.Event,
  CustomEvent: window.CustomEvent,
  MouseEvent: window.MouseEvent,
  KeyboardEvent: window.KeyboardEvent,
  FocusEvent: window.FocusEvent,
  InputEvent: window.InputEvent,
  getComputedStyle: window.getComputedStyle.bind(window),
  requestAnimationFrame: window.requestAnimationFrame.bind(window),
  cancelAnimationFrame: window.cancelAnimationFrame.bind(window),
  setTimeout: window.setTimeout.bind(window),
  clearTimeout: window.clearTimeout.bind(window),
  setInterval: window.setInterval.bind(window),
  clearInterval: window.clearInterval.bind(window),
  MutationObserver: window.MutationObserver,
  ResizeObserver: window.ResizeObserver,
  IntersectionObserver: window.IntersectionObserver,
  URL: window.URL,
  URLSearchParams: window.URLSearchParams,
  Headers: window.Headers,
  Request: window.Request,
  Response: window.Response,
  fetch: window.fetch.bind(window),
  FormData: window.FormData,
  Blob: window.Blob,
  File: window.File,
  FileReader: window.FileReader,
  DOMParser: window.DOMParser,
  XMLSerializer: window.XMLSerializer,
  Range: window.Range,
  Selection: window.Selection,
  Storage: window.Storage,
  localStorage: window.localStorage,
  sessionStorage: window.sessionStorage,
});
