// =============================================================================
// Ollama Library Models
// =============================================================================
// Auto-generated from model database
// Run: gleam run -m scrape_models
// =============================================================================

pub type OllamaModel {
  OllamaModel(
    name: String,
    description: String,
    pulls: Int,
    tags: List(String),
  )
}

pub fn get_all_models() -> List(OllamaModel) {
  [
    OllamaModel("llama3.1", "Meta's Llama 3.1 available in 8B, 70B, 405B sizes", 20_000_000, ["large", "chat"]),
    OllamaModel("llama3.2", "Meta's compact models (1B, 3B) for efficient performance", 15_000_000, ["small", "chat"]),
    OllamaModel("mistral", "Mistral 7B v0.3 - Excellent reasoning", 12_000_000, ["reasoning"]),
    OllamaModel("llama3", "Meta Llama 3 - Most capable openly available LLM", 10_000_000, ["chat"]),
    OllamaModel("llama3.3", "Meta's 70B state-of-the-art model with 405B-equivalent performance", 8_000_000, ["large", "chat"]),
    OllamaModel("llama2", "Meta Llama 2 foundation models (7B-70B)", 8_000_000, ["large", "chat"]),
    OllamaModel("nomic-embed-text", "Nomic Embed Text - High-performing embeddings", 8_000_000, ["embedding"]),
    OllamaModel("qwen2.5", "Qwen 2.5 - 18T tokens, 128K context models", 6_000_000, ["chat"]),
    OllamaModel("gemma2", "Google Gemma 2 - High-performing efficient models", 6_000_000, ["chat"]),
    OllamaModel("phi3", "Microsoft Phi-3 - Lightweight state-of-the-art", 6_000_000, ["small", "chat"]),
    OllamaModel("codellama", "Code Llama - Generates and discusses code", 6_000_000, ["code"]),
    OllamaModel("deepseek-r1", "DeepSeek R1 - Open reasoning model near O3/Gemini 2.5 Pro", 5_000_000, ["small", "reasoning"]),
    OllamaModel("gemma3", "Google Gemma 3 - Most capable single-GPU model", 5_000_000, ["chat"]),
    OllamaModel("gemma", "Google Gemma v1.1 - Lightweight open models", 5_000_000, ["small", "chat"]),
    OllamaModel("phi", "Phi-2 - Outstanding reasoning capabilities", 5_000_000, ["reasoning"]),
    OllamaModel("mixtral", "Mixtral MoE - Open-weight mixture of experts", 5_000_000, ["moe", "chat"]),
    OllamaModel("tinyllama", "TinyLlama 1.1B - Trained on 3T tokens", 5_000_000, ["small", "chat"]),
    OllamaModel("qwen3", "Qwen 3 - Latest generation dense and MoE models", 4_000_000, ["moe", "chat"]),
    OllamaModel("qwen2.5-coder", "Qwen 2.5 Coder - Code specialist models", 4_000_000, ["code"]),
    OllamaModel("qwen2", "Qwen 2 - Alibaba language model series", 4_000_000, ["chat"]),
    OllamaModel("phi4", "Microsoft Phi-4 14B - State-of-the-art open model", 4_000_000, ["chat"]),
    OllamaModel("mistral-nemo", "Mistral Nemo 12B - 128k context by NVIDIA", 4_000_000, ["small", "chat"]),
    OllamaModel("llava", "LLaVA - Vision encoder with language understanding", 4_000_000, ["code", "vision"]),
    OllamaModel("mxbai-embed-large", "MixedBread Embed Large - State-of-the-art", 4_000_000, ["embedding"]),
    OllamaModel("llama2-uncensored", "Llama 2 uncensored by George Sung", 3_000_000, ["uncensored", "chat"]),
    OllamaModel("deepseek-coder", "DeepSeek Coder - Trained on 2T code tokens", 3_000_000, ["code"]),
    OllamaModel("qwen", "Qwen - Alibaba Cloud series (0.5B-110B)", 3_000_000, ["small", "large", "chat"]),
    OllamaModel("codegemma", "CodeGemma - Lightweight coding tasks", 3_000_000, ["small", "code"]),
    OllamaModel("all-minilm", "All-MiniLM - Fast sentence embeddings", 3_000_000, ["small", "embedding"]),
    OllamaModel("vicuna", "Vicuna - General chat model", 3_000_000, ["chat"]),
    OllamaModel("zephyr", "Zephyr - Fine-tuned as helpful assistant", 3_000_000, ["chat"]),
    OllamaModel("phi3.5", "Phi-3.5 - Overtaking larger model performance", 2_500_000, ["chat"]),
    OllamaModel("mistral-small", "Mistral Small - Benchmark-setting small LLM", 2_500_000, ["small", "chat"]),
    OllamaModel("starcoder", "StarCoder - 80+ programming languages", 2_500_000, ["code"]),
    OllamaModel("smollm2", "SmolLM 2 - Updated compact family", 2_500_000, ["small", "chat"]),
    OllamaModel("openchat", "OpenChat v3.5 - Surpasses ChatGPT", 2_500_000, ["chat"]),
    OllamaModel("falcon", "Falcon - TII summarization and chat", 2_500_000, ["chat"]),
    OllamaModel("orca-mini", "Orca Mini - General purpose", 2_500_000, ["small", "chat"]),
    OllamaModel("llama3.2-vision", "Llama 3.2 Vision - Instruction-tuned image reasoning", 2_000_000, ["vision", "reasoning"]),
    OllamaModel("deepseek-v3", "DeepSeek V3 - Strong MoE with 671B parameters", 2_000_000, ["small", "large", "moe", "chat"]),
    OllamaModel("qwq", "QwQ - Reasoning model in Qwen series", 2_000_000, ["reasoning"]),
    OllamaModel("phi4-mini", "Phi-4 Mini - Multilingual and function calling", 2_000_000, ["small", "multilingual", "tools"]),
    OllamaModel("codestral", "Codestral - Mistral's code generation model", 2_000_000, ["code"]),
    OllamaModel("starcoder2", "StarCoder2 - Next-gen transparent code LLM", 2_000_000, ["code"]),
    OllamaModel("bge-m3", "BGE M3 - Multi-functionality embeddings", 2_000_000, ["embedding", "tools"]),
    OllamaModel("dolphin3", "Dolphin 3 - Next-gen instruct-tuned model", 2_000_000, ["uncensored", "chat"]),
    OllamaModel("dolphin-mixtral", "Dolphin Mixtral - Uncensored MoE coding", 2_000_000, ["code", "uncensored", "moe"]),
    OllamaModel("dolphin-mistral", "Dolphin Mistral v2.8 - Uncensored coding", 2_000_000, ["code", "uncensored"]),
    OllamaModel("hermes3", "Hermes 3 - Nous Research flagship", 2_000_000, ["chat"]),
    OllamaModel("nous-hermes", "Nous Hermes - General models", 2_000_000, ["chat"]),
    OllamaModel("openhermes", "OpenHermes - Fine-tuned on Mistral", 2_000_000, ["chat"]),
    OllamaModel("smollm", "SmolLM - Small family (135M-1.7B)", 2_000_000, ["small", "chat"]),
    OllamaModel("yi", "Yi - High-performing bilingual model", 2_000_000, ["chat"]),
    OllamaModel("wizardlm", "WizardLM - General purpose", 2_000_000, ["chat"]),
    OllamaModel("deepseek-v3.1", "DeepSeek V3.1 - Hybrid thinking/non-thinking modes", 1_500_000, ["reasoning"]),
    OllamaModel("deepseek-v2", "DeepSeek V2 - Economical MoE language model", 1_500_000, ["moe", "chat"]),
    OllamaModel("deepseek-coder-v2", "DeepSeek Coder V2 - MoE comparable to GPT4-Turbo", 1_500_000, ["code", "moe"]),
    OllamaModel("codeqwen", "CodeQwen - Pretrained on large code data", 1_500_000, ["code"]),
    OllamaModel("mistral-small3.1", "Mistral Small 3.1 - Vision and 128k context", 1_500_000, ["small", "vision"]),
    OllamaModel("stable-code", "Stable Code - Matches 7B Code Llama", 1_500_000, ["code"]),
    OllamaModel("llava-llama3", "LLaVA Llama3 - Improved benchmark scores", 1_500_000, ["vision"]),
    OllamaModel("moondream", "Moondream - Small vision for edge devices", 1_500_000, ["small", "vision"]),
    OllamaModel("bge-large", "BGE Large - Text to vector mapping", 1_500_000, ["embedding"]),
    OllamaModel("snowflake-arctic-embed", "Snowflake Arctic Embed - Performance optimized", 1_500_000, ["embedding"]),
    OllamaModel("dolphin-llama3", "Dolphin Llama 3 - By Eric Hartford", 1_500_000, ["uncensored", "chat"]),
    OllamaModel("dolphin-phi", "Dolphin Phi - Uncensored based on Phi", 1_500_000, ["uncensored", "chat"]),
    OllamaModel("nous-hermes2", "Nous Hermes 2 - Scientific and coding", 1_500_000, ["code"]),
    OllamaModel("olmo2", "OLMo 2 - Trained on 5T tokens", 1_500_000, ["chat"]),
    OllamaModel("neural-chat", "Neural Chat - Fine-tuned Mistral", 1_500_000, ["chat"]),
    OllamaModel("solar", "Solar 10.7B - Single-turn conversation", 1_500_000, ["chat"]),
    OllamaModel("command-r", "Cohere Command-R - Conversational and long context", 1_500_000, ["chat"]),
    OllamaModel("orca2", "Orca 2 - Microsoft fine-tuned reasoning", 1_500_000, ["reasoning"]),
    OllamaModel("wizardlm2", "WizardLM 2 - Chat and reasoning", 1_500_000, ["reasoning"]),
    OllamaModel("wizard-vicuna-uncensored", "Wizard Vicuna Uncensored", 1_500_000, ["uncensored", "chat"]),
    OllamaModel("stablelm2", "StableLM 2 - Multilingual", 1_500_000, ["multilingual", "chat"]),
    OllamaModel("qwen2.5vl", "Qwen 2.5 VL - Flagship vision-language model", 1_200_000, ["vision"]),
    OllamaModel("phind-codellama", "Phind CodeLlama - Code generation", 1_200_000, ["code"]),
    OllamaModel("bakllava", "BakLLaVA - Mistral with LLaVA architecture", 1_200_000, ["vision"]),
    OllamaModel("starling-lm", "Starling LM - RLHF trained", 1_200_000, ["chat"]),
    OllamaModel("falcon2", "Falcon 2 - 11B trained on 5T tokens", 1_200_000, ["small", "chat"]),
    OllamaModel("glm4", "GLM-4 - Strong multi-lingual model", 1_200_000, ["multilingual", "chat"]),
    OllamaModel("deepseek-v2.5", "DeepSeek V2.5 - Combined general and coding abilities", 1_000_000, ["code"]),
    OllamaModel("deepseek-llm", "DeepSeek LLM - Bilingual language model", 1_000_000, ["chat"]),
    OllamaModel("mistral-small3.2", "Mistral Small 3.2 - Improved function calling", 1_000_000, ["small", "tools"]),
    OllamaModel("mistral-large", "Mistral Large - Flagship 123B with 128k context", 1_000_000, ["small", "large", "chat"]),
    OllamaModel("wizardcoder", "WizardCoder - State-of-the-art code generation", 1_000_000, ["code"]),
    OllamaModel("sqlcoder", "SQLCoder - SQL generation specialist", 1_000_000, ["code", "sql"]),
    OllamaModel("codegeex4", "CodeGeeX4 - AI software development", 1_000_000, ["code"]),
    OllamaModel("dolphincoder", "DolphinCoder - Uncensored coding", 1_000_000, ["code"]),
    OllamaModel("llava-phi3", "LLaVA Phi3 - Small vision model", 1_000_000, ["small", "vision"]),
    OllamaModel("minicpm-v", "MiniCPM-V - Vision-language understanding", 1_000_000, ["small", "vision"]),
    OllamaModel("tinydolphin", "TinyDolphin - Experimental 1.1B Dolphin", 1_000_000, ["small", "uncensored", "chat"]),
    OllamaModel("nous-hermes2-mixtral", "Nous Hermes 2 Mixtral - Trained over Mixtral", 1_000_000, ["chat"]),
    OllamaModel("granite-code", "Granite Code - IBM code intelligence", 1_000_000, ["code"]),
    OllamaModel("falcon3", "Falcon 3 - Efficient for science/math", 1_000_000, ["reasoning"]),
    OllamaModel("command-r7b", "Cohere Command-R 7B - Efficient quality", 1_000_000, ["chat"]),
    OllamaModel("wizardlm-uncensored", "WizardLM Uncensored", 1_000_000, ["uncensored", "chat"]),
    OllamaModel("stable-beluga", "Stable Beluga - Orca-style fine-tuned", 1_000_000, ["chat"]),
    OllamaModel("stablelm-zephyr", "StableLM Zephyr - Lightweight chat", 1_000_000, ["small", "chat"]),
    OllamaModel("llama-guard3", "Llama Guard 3 - Content safety classification", 800_000, ["safety"]),
    OllamaModel("qwen2-math", "Qwen 2 Math - Specialized math models", 800_000, ["reasoning"]),
    OllamaModel("mistral-openorca", "Mistral OpenOrca - Fine-tuned on OpenOrca", 800_000, ["chat"]),
    OllamaModel("yi-coder", "Yi Coder - Open-source coding models", 800_000, ["code"]),
    OllamaModel("magicoder", "Magicoder - Synthetic instruction data", 800_000, ["code"]),
    OllamaModel("paraphrase-multilingual", "Paraphrase Multilingual - Clustering and search", 800_000, ["multilingual", "chat"]),
    OllamaModel("olmo-3", "OLMo 3 - Dolma 3 dataset", 800_000, ["chat"]),
    OllamaModel("solar-pro", "Solar Pro 22B - Single GPU advanced", 800_000, ["small", "chat"]),
    OllamaModel("command-r-plus", "Cohere Command-R Plus - Enterprise use cases", 800_000, ["chat"]),
    OllamaModel("aya", "Aya - 23 languages by Cohere", 800_000, ["multilingual", "chat"]),
    OllamaModel("wizard-vicuna", "Wizard Vicuna - Based on Llama 2", 800_000, ["chat"]),
    OllamaModel("xwinlm", "XWin-LM - Competitive conversational", 800_000, ["chat"]),
    OllamaModel("opencoder", "OpenCoder - Reproducible code LLM", 700_000, ["code"]),
    OllamaModel("aya-expanse", "Aya Expanse - 23 languages trained", 700_000, ["multilingual", "chat"]),
    OllamaModel("samantha-mistral", "Samantha Mistral - Companion trained", 700_000, ["chat"]),
    OllamaModel("llama2-chinese", "Llama 2 fine-tuned for Chinese dialogue", 600_000, ["multilingual", "chat"]),
    OllamaModel("deepcoder", "DeepCoder - Fine-tuned coder at O3-mini level", 600_000, ["small", "code"]),
    OllamaModel("devstral", "Devstral - Best open-source coding agent", 600_000, ["code", "tools"]),
    OllamaModel("granite-embedding", "Granite Embedding - IBM biencoder", 600_000, ["code", "embedding"]),
    OllamaModel("granite3-dense", "Granite 3 Dense - Tool-based and RAG", 600_000, ["tools"]),
    OllamaModel("wizard-math", "Wizard Math - Math and logic", 600_000, ["reasoning"]),
    OllamaModel("internlm2", "InternLM2 - Practical scenarios with reasoning", 600_000, ["reasoning"]),
    OllamaModel("exaone3.5", "EXAONE 3.5 - Bilingual by LG", 600_000, ["chat"]),
    OllamaModel("openthinker", "OpenThinker - Distilled from DeepSeek-R1", 600_000, ["reasoning"]),
    OllamaModel("llama3-chatqa", "Llama 3 ChatQA - Conversational QA and RAG", 600_000, ["chat"]),
    OllamaModel("yarn-mistral", "YARN Mistral - 64K/128K context", 600_000, ["chat"]),
    OllamaModel("everythinglm", "EverythingLM - 16K context uncensored", 600_000, ["uncensored", "chat"]),
    OllamaModel("llama4", "Meta Llama 4 - Latest multimodal collection", 500_000, ["chat"]),
    OllamaModel("llama-pro", "Llama Pro - Expanded with programming and math", 500_000, ["reasoning"]),
    OllamaModel("deepseek-v3.2", "DeepSeek V3.2 - Harmonized efficiency with reasoning", 500_000, ["reasoning"]),
    OllamaModel("qwen3-coder", "Qwen 3 Coder - Agentic and coding tasks", 500_000, ["code", "tools"]),
    OllamaModel("gemma3n", "Gemma 3N - Designed for everyday devices", 500_000, ["chat"]),
    OllamaModel("shieldgemma", "ShieldGemma - Safety evaluation models", 500_000, ["safety"]),
    OllamaModel("phi4-reasoning", "Phi-4 Reasoning - Rivaling larger models", 500_000, ["reasoning"]),
    OllamaModel("mistral-large-3", "Mistral Large 3 - Multimodal MoE", 500_000, ["moe", "chat"]),
    OllamaModel("mathstral", "Mathstral - Math reasoning and discovery", 500_000, ["reasoning"]),
    OllamaModel("duckdb-nsql", "DuckDB NSQL - Text-to-SQL model", 500_000, ["sql"]),
    OllamaModel("codebooga", "CodeBooga - High-performing code merge", 500_000, ["code"]),
    OllamaModel("nomic-embed-text-v2-moe", "Nomic Embed V2 MoE - Multilingual", 500_000, ["embedding", "multilingual", "moe"]),
    OllamaModel("snowflake-arctic-embed2", "Snowflake Arctic Embed 2 - Frontier multilingual", 500_000, ["embedding", "multilingual"]),
    OllamaModel("granite3.1-dense", "Granite 3.1 Dense - 12T tokens trained", 500_000, ["chat"]),
    OllamaModel("granite3.2", "Granite 3.2 - Thinking capabilities", 500_000, ["reasoning"]),
    OllamaModel("glm-4.6", "GLM-4.6 - Advanced agentic and reasoning", 500_000, ["reasoning", "tools"]),
    OllamaModel("command-r7b-arabic", "Cohere Command-R 7B Arabic - Arabic language", 500_000, ["multilingual", "chat"]),
    OllamaModel("dbrx", "DBRX - Databricks open LLM", 500_000, ["chat"]),
    OllamaModel("exaone-deep", "EXAONE Deep - Superior reasoning by LG", 500_000, ["reasoning"]),
    OllamaModel("cogito", "Cogito - Hybrid reasoning models", 500_000, ["reasoning"]),
    OllamaModel("smallthinker", "SmallThinker - Fine-tuned from Qwen 2.5", 500_000, ["small", "reasoning"]),
    OllamaModel("nemotron-mini", "Nemotron Mini - Roleplay and RAG by NVIDIA", 500_000, ["small", "chat"]),
    OllamaModel("reader-lm", "Reader LM - HTML to Markdown conversion", 500_000, ["chat"]),
    OllamaModel("meditron", "Meditron - Medical domain Llama 2", 500_000, ["medical"]),
    OllamaModel("llama3-groq-tool-use", "Llama 3 Groq Tool Use - Open-source tools", 500_000, ["tools"]),
    OllamaModel("llama3-gradient", "Llama 3 Gradient - 1M+ token context", 500_000, ["chat"]),
    OllamaModel("yarn-llama2", "YARN Llama 2 - 128k context", 500_000, ["chat"]),
    OllamaModel("gpt-oss", "GPT-OSS - OpenAI's open-weight reasoning", 500_000, ["reasoning"]),
    OllamaModel("granite3.1-moe", "Granite 3.1 MoE - Long-context MoE", 450_000, ["moe", "chat"]),
    OllamaModel("deepscaler", "DeepScaler - Exceeds o1-preview performance", 400_000, ["reasoning"]),
    OllamaModel("qwen3-vl", "Qwen 3 VL - Most powerful Qwen vision-language", 400_000, ["vision"]),
    OllamaModel("embeddinggemma", "Embedding Gemma - 300M embedding model", 400_000, ["embedding"]),
    OllamaModel("phi4-mini-reasoning", "Phi-4 Mini Reasoning - Lightweight reasoning", 400_000, ["small", "reasoning"]),
    OllamaModel("mistrallite", "MistralLite - Long context processing", 400_000, ["chat"]),
    OllamaModel("codeup", "CodeUp - Code generation based on Llama2", 400_000, ["code"]),
    OllamaModel("granite3.2-vision", "Granite 3.2 Vision - Document understanding", 400_000, ["vision"]),
    OllamaModel("granite3-moe", "Granite 3 MoE - First Granite MoE", 400_000, ["moe", "chat"]),
    OllamaModel("granite3.3", "Granite 3.3 - 128K context reasoning", 400_000, ["reasoning"]),
    OllamaModel("granite3-guardian", "Granite 3 Guardian - Risk detection", 400_000, ["safety"]),
    OllamaModel("olmo-3.1", "OLMo 3.1 - Latest from Dolma 3", 400_000, ["chat"]),
    OllamaModel("command-a", "Cohere Command-A - Enterprise optimized", 400_000, ["chat"]),
    OllamaModel("sailor2", "Sailor 2 - South-East Asian multilingual", 400_000, ["multilingual", "chat"]),
    OllamaModel("tulu3", "Tulu 3 - Instruction-following by Allen AI", 400_000, ["chat"]),
    OllamaModel("marco-o1", "Marco-o1 - Open reasoning by Alibaba", 400_000, ["reasoning"]),
    OllamaModel("nuextract", "NuExtract - Information extraction", 400_000, ["chat"]),
    OllamaModel("medllama2", "MedLlama2 - Medical questions", 400_000, ["medical"]),
    OllamaModel("nexusraven", "NexusRaven - Function calling tasks", 400_000, ["tools"]),
    OllamaModel("notus", "Notus - High-quality data fine-tuned", 400_000, ["chat"]),
    OllamaModel("open-orca-platypus2", "Open Orca Platypus2 - Chat and code", 400_000, ["code"]),
    OllamaModel("deepseek-ocr", "DeepSeek OCR - Vision-language for token-efficient OCR", 300_000, ["vision"]),
    OllamaModel("qwen3-embedding", "Qwen 3 Embedding - Comprehensive text embeddings", 300_000, ["embedding"]),
    OllamaModel("devstral-small-2", "Devstral Small 2 - Code exploration 24B", 300_000, ["small", "code"]),
    OllamaModel("magistral", "Magistral - Efficient 24B reasoning model", 300_000, ["reasoning"]),
    OllamaModel("granite4", "Granite 4 - Improved instruction following", 300_000, ["chat"]),
    OllamaModel("glm-4.7", "GLM-4.7 - Improved coding capability", 300_000, ["code"]),
    OllamaModel("reflection", "Reflection - Reflection-tuning technique", 300_000, ["chat"]),
    OllamaModel("athene-v2", "Athene V2 - Code and math excellence", 300_000, ["code", "reasoning"]),
    OllamaModel("nemotron", "Nemotron - NVIDIA customized for helpfulness", 300_000, ["chat"]),
    OllamaModel("firefunction-v2", "FireFunction V2 - Function calling on Llama 3", 300_000, ["tools"]),
    OllamaModel("notux", "Notux - Top MoE fine-tuned", 300_000, ["moe", "chat"]),
    OllamaModel("goliath", "Goliath - Combined Llama 2 70B", 300_000, ["large", "chat"]),
    OllamaModel("alfred", "Alfred - Robust conversational", 300_000, ["chat"]),
    OllamaModel("bespoke-minicheck", "Bespoke MiniCheck - Fact-checking", 300_000, ["small", "chat"]),
    OllamaModel("minimax-m2", "MiniMax M2 - Coding workflows", 300_000, ["small", "code"]),
    OllamaModel("ministral-3", "Ministral 3 - Edge deployment", 300_000, ["small", "chat"]),
    OllamaModel("kimi-k2", "Kimi K2 - State-of-the-art MoE", 300_000, ["moe", "chat"]),
    OllamaModel("functiongemma", "FunctionGemma - Function calling fine-tuned", 200_000, ["tools"]),
    OllamaModel("megadolphin", "MegaDolphin - 120B interleaved Dolphin", 200_000, ["large", "uncensored", "chat"]),
    OllamaModel("cogito-2.1", "Cogito 2.1 - Instruction-tuned under MIT", 200_000, ["chat"]),
    OllamaModel("r1-1776", "R1-1776 - Unbiased factual DeepSeek-R1", 200_000, ["reasoning"]),
    OllamaModel("nemotron-3-nano", "Nemotron 3 Nano - Agentic model by NVIDIA", 200_000, ["small", "tools"]),
    OllamaModel("gpt-oss-safeguard", "GPT-OSS Safeguard - Safety reasoning", 200_000, ["reasoning", "safety"]),
    OllamaModel("gemini-3-pro-preview", "Gemini 3 Pro Preview - Google reasoning", 200_000, ["small", "reasoning"]),
    OllamaModel("gemini-3-flash-preview", "Gemini 3 Flash Preview - High-speed", 200_000, ["small", "chat"]),
    OllamaModel("kimi-k2-thinking", "Kimi K2 Thinking - Moonshot thinking model", 200_000, ["reasoning"]),
    OllamaModel("qwen3-next", "Qwen3-Next - Parameter efficiency and speed", 200_000, ["chat"]),
    OllamaModel("devstral-2", "Devstral 2 - File editing agent 123B", 150_000, ["small", "large", "code", "tools"]),
    OllamaModel("minimax-m2.1", "MiniMax M2.1 - Multilingual code engineering", 100_000, ["small", "code", "multilingual"]),
    OllamaModel("rnj-1", "RNJ-1 - 8B optimized for code and STEM", 100_000, ["code"])
  ]
}
