#!/usr/bin/env python3
"""
Voiz Web Installer - Backend API

Provides a web interface for configuring and installing the Voiz AI stack.
"""

import os
import json
import subprocess
import time
from pathlib import Path
from flask import Flask, render_template, request, jsonify, Response

app = Flask(__name__)

# Paths
PROJECT_ROOT = Path(__file__).parent.parent
ENV_FILE = PROJECT_ROOT / '.env'
AUTH_DIR = PROJECT_ROOT / 'auth'
AUTH_FILE = AUTH_DIR / 'users.htpasswd'


@app.route('/')
def index():
    """Serve the installer UI."""
    return render_template('index.html')


@app.route('/api/install', methods=['POST'])
def install():
    """
    Handle installation request.
    Receives configuration, writes .env file, and runs setup.
    """
    try:
        config = request.json

        def generate_updates():
            """Generator for streaming installation progress."""

            # Step 1: Validate configuration
            yield json.dumps({'status': '✓ Configuration received', 'progress': 10}) + '\n'
            time.sleep(0.5)

            # Step 2: Write .env file
            yield json.dumps({'status': 'Writing .env file...', 'progress': 20}) + '\n'
            try:
                write_env_file(config)
                yield json.dumps({'status': '✓ .env file created', 'progress': 40}) + '\n'
            except Exception as e:
                yield json.dumps({'error': f'Failed to write .env file: {str(e)}'}) + '\n'
                return

            time.sleep(0.5)

            # Step 3: Create auth directory
            yield json.dumps({'status': 'Creating auth directory...', 'progress': 50}) + '\n'
            try:
                AUTH_DIR.mkdir(parents=True, exist_ok=True)
                yield json.dumps({'status': '✓ Auth directory created', 'progress': 60}) + '\n'
            except Exception as e:
                yield json.dumps({'error': f'Failed to create auth directory: {str(e)}'}) + '\n'
                return

            time.sleep(0.5)

            # Step 4: Generate basic auth file
            yield json.dumps({'status': 'Generating basic authentication...', 'progress': 70}) + '\n'
            try:
                # Create a default admin user with password "admin"
                # User should change this after first login
                result = subprocess.run(
                    ['htpasswd', '-nbB', 'admin', 'admin'],
                    capture_output=True,
                    text=True,
                    check=True
                )
                AUTH_FILE.write_text(result.stdout)
                yield json.dumps({'status': '✓ Basic auth created (user: admin, password: admin)', 'progress': 80}) + '\n'
            except subprocess.CalledProcessError as e:
                yield json.dumps({'error': f'Failed to create auth: {str(e)}'}) + '\n'
                return
            except Exception as e:
                yield json.dumps({'error': f'Unexpected error creating auth: {str(e)}'}) + '\n'
                return

            time.sleep(0.5)

            # Step 5: Validate Docker Compose config
            yield json.dumps({'status': 'Validating Docker Compose configuration...', 'progress': 90}) + '\n'
            try:
                result = subprocess.run(
                    ['docker', 'compose', 'config', '--quiet'],
                    cwd=PROJECT_ROOT,
                    capture_output=True,
                    text=True,
                    timeout=10
                )
                if result.returncode == 0:
                    yield json.dumps({'status': '✓ Docker Compose configuration valid', 'progress': 95}) + '\n'
                else:
                    yield json.dumps({'status': f'Warning: Docker Compose validation had issues', 'progress': 95}) + '\n'
            except Exception as e:
                yield json.dumps({'status': f'Warning: Could not validate Docker Compose: {str(e)}', 'progress': 95}) + '\n'

            time.sleep(0.5)

            # Step 6: Complete
            yield json.dumps({
                'status': '✓ Installation complete!',
                'progress': 100,
                'complete': True
            }) + '\n'

        return Response(generate_updates(), mimetype='application/json')

    except Exception as e:
        return jsonify({'error': str(e)}), 500


def write_env_file(config):
    """Write configuration to .env file."""

    lines = [
        '# =============================================================================',
        '# VOIZ - Self-Hosted AI Stack Configuration',
        '# =============================================================================',
        '# Generated by Web Installer',
        '# =============================================================================',
        '',
        '# -----------------------------------------------------------------------------',
        '# DOMAIN_* - Domain Configuration',
        '# -----------------------------------------------------------------------------',
    ]

    # Group variables by prefix
    groups = {
        'DOMAIN_': [],
        'SECURITY_': [],
        'OLLAMA_': [],
        'WEBUI_': [],
        'SEARCH_': [],
        'VPN_': [],
        'ADVANCED_': []
    }

    # Sort config into groups
    for key, value in sorted(config.items()):
        for prefix in groups.keys():
            if key.startswith(prefix):
                groups[prefix].append((key, value))
                break

    # Write each group
    group_headers = {
        'DOMAIN_': ('# DOMAIN_* - Domain Configuration', ''),
        'SECURITY_': ('# SECURITY_* - Security & Authentication', ''),
        'OLLAMA_': ('# OLLAMA_* - Model Configuration', ''),
        'WEBUI_': ('# WEBUI_* - Open WebUI Configuration', ''),
        'SEARCH_': ('# SEARCH_* - Web Search Configuration', ''),
        'VPN_': ('# VPN_* - VPN Configuration (Optional)', ''),
        'ADVANCED_': ('# ADVANCED_* - Advanced Configuration', '')
    }

    for prefix, (header, comment) in group_headers.items():
        if groups[prefix]:
            lines.extend(['', '# ' + '-' * 77, header, '# ' + '-' * 77])
            if comment:
                lines.append('# ' + comment)

            for key, value in groups[prefix]:
                # Handle empty values
                if value == '':
                    lines.append(f'{key}=')
                # Handle boolean values
                elif value in ('true', 'false'):
                    lines.append(f'{key}={value}')
                # Handle values that need quotes
                elif ' ' in str(value) or '<' in str(value) or '>' in str(value):
                    lines.append(f'{key}="{value}"')
                # Handle regular values
                else:
                    lines.append(f'{key}={value}')

    lines.append('')  # Final newline

    # Write to file
    ENV_FILE.write_text('\n'.join(lines))


if __name__ == '__main__':
    app.run(host='0.0.0.0', port=8000, debug=True)
